# Generated by Django 4.1 on 2022-10-12 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('idprice', models.AutoField(primary_key=True, serialize=False)),
                ('buyprice', models.IntegerField(blank=True, null=True)),
                ('renew_bp_date', models.DateField(blank=True, null=True)),
                ('sellprice', models.IntegerField(blank=True, null=True)),
                ('renew_sp_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'price',
                'managed': False,
            },
        ),
    ]
