# Generated by Django 4.1 on 2022-10-12 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={},
        ),
    ]
