# Generated by Django 4.1 on 2022-10-17 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0002_alter_price_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={'managed': False},
        ),
    ]
