# Generated by Django 4.1 on 2022-10-05 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('company', models.CharField(blank=True, max_length=50, null=True)),
                ('product', models.CharField(blank=True, max_length=50, null=True)),
                ('count', models.IntegerField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=10, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('sumprice', models.IntegerField(blank=True, null=True)),
                ('tax', models.IntegerField(blank=True, null=True)),
                ('totalprice', models.IntegerField(blank=True, null=True)),
                ('inoutcompany', models.CharField(blank=True, max_length=50, null=True)),
                ('incomeprice', models.IntegerField(blank=True, null=True)),
                ('division', models.CharField(blank=True, choices=[('매입', '매입'), ('매출', '매출'), ('매출반품', '매출반품'), ('매입반품', '매입반품')], default='매출', max_length=10, null=True)),
                ('paymethod', models.CharField(blank=True, max_length=45, null=True)),
                ('remark', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'acount',
                'managed': False,
            },
        ),
    ]
