# Generated by Django 4.1 on 2022-09-17 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('comnum', models.CharField(blank=True, max_length=30, null=True)),
                ('ceo', models.CharField(blank=True, max_length=30, null=True)),
                ('tel', models.CharField(blank=True, max_length=50, null=True)),
                ('fax', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('type', models.CharField(blank=True, max_length=10, null=True)),
                ('item', models.CharField(blank=True, max_length=30, null=True)),
                ('delivery', models.CharField(blank=True, max_length=200, null=True)),
                ('cellphone', models.CharField(blank=True, max_length=30, null=True)),
                ('post', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('division', models.CharField(blank=True, max_length=10, null=True)),
                ('remark', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'company',
                'managed': False,
            },
        ),
    ]
