# Generated by Django 4.1 on 2022-10-12 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VMoney',
            fields=[
                ('id_v_money', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('deposit', models.IntegerField(blank=True, null=True)),
                ('expense', models.IntegerField(blank=True, null=True)),
                ('remark', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'v_money',
                'managed': False,
            },
        ),
    ]
