# Generated by Django 4.1 on 2022-10-06 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('idproducts', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(blank=True, db_collation='utf8mb4_unicode_ci', max_length=45, null=True)),
                ('p_name', models.CharField(blank=True, db_collation='utf8mb4_unicode_ci', max_length=45, null=True)),
            ],
            options={
                'db_table': 'products',
                'managed': False,
            },
        ),
    ]
